language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yursov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yursov/react-test npm test

after_success:
  - docker build -t yursov/multi-client ./client
  - docker build -t yursov/multi-nginx ./nginx
  - docker build -t yursov/multi-server ./server
  - docker build -t yursov/multi-worker ./worker
# Login into Docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push yursov/multi-client
  - docker push yursov/multi-nginx
  - docker push yursov/multi-server
  - docker push yursov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-962795369625'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY